db_uri: "postgresql://parameshwaraniyer@localhost:5432/chinook"
schema: "public"
output_filename: "output/full_schema_classification.csv"
dotenv_path: ".env"        # Path to your .env file (relative to where you run your script)
openai_model: "gpt-3.5-turbo"          # Model to use (can be gpt-4, gpt-4o, gpt-3.5-turbo, etc.)
dama_categories:
  - pii
  - confidential
  - internal
  - sensitive
  - public
  - restricted
  - sensitive-personal
  - sensitive-health
  - financial
  - regulatory
  - proprietary
  - general